export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const GET_PROFILE = "GET_PROFILE";
export const GET_RESTAURANT_PROFILE = "GET_RESTAURANT_PROFILE";
export const RESTAURANT_PROFILE_ERROR = "RESTAURANT_PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const GET_RESTAURANTS_PRODUCTS = "GET_RESTAURANTS_PRODUCTS";
export const GET_RESTAURANTS_PRODUCTS_ERROR = "GET_RESTAURANTS_PRODUCTS_ERROR";
export const RESTAURANTS_ERROR = "RESTAURANTS_ERROR";

//
export const GET_RESTAURANTS_PRODUCTS_BY_ID = "GET_RESTAURANTS_PRODUCTS_BY_ID";
export const GET_RESTAURANTS_PRODUCTS_BY_ID_ERROR =
  "GET_RESTAURANTS_PRODUCTS_BY_ID_ERROR";

// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
